spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: never
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        bindings:
          newOrderMessageConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
          newOrderMessageProducer-out-0:
            producer:
              configuration:
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                schema.registry.url: http://localhost:8081
      bindings:
        newOrderMessageConsumer-in-0:
          destination: new-order-message
          group: 1
          consumer:
            use-native-decoding: true
        newOrderMessageProducer-out-0:
          destination: new-order-message
          producer:
            use-native-encoding: true
